# ***Pandas Questions & Answers Using Seaborn's healthexp Dataset***

- Loading the Libraries

In [1]:
import pandas as pd
import seaborn as sns

- Loading the Dataset

In [30]:
df = sns.load_dataset("healthexp")
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

- Display first 10 rows.

In [3]:
df.head(10)

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9
5  1971         Canada       313.391             72.8
6  1971        Germany       298.251             70.8
7  1971  Great Britain       134.172             71.9
8  1971          Japan       163.854             72.9
9  1971            USA       357.988             71.2

Display last 10 rows.

In [4]:
df.tail(10)

     Year        Country  Spending_USD  Life_Expectancy
264  2019         France      5167.839             82.9
265  2019  Great Britain      4385.463             81.4
266  2019          Japan      4610.794             84.4
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

- Display dataset shape.

In [5]:
df.shape

(274, 4)

- Count rows.

In [6]:
len(df)

274

- Display column names

In [7]:
df.columns

Index(['Year', 'Country', 'Spending_USD', 'Life_Expectancy'], dtype='object')

- Show data types

In [8]:
df.dtypes

Year                 int64
Country             object
Spending_USD       float64
Life_Expectancy    float64
dtype: object

- Get dataset information.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             274 non-null    int64
 1   Country          274 non-null    object
 2   Spending_USD     274 non-null    float64
 3   Life_Expectancy  274 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 8.7+ KB

- Display summary statistics

In [10]:
df.describe()

              Year  Spending_USD  Life_Expectancy
count   274.000000    274.000000       274.000000
mean   1996.992701   2789.338905        77.909489
std      14.180933   2194.939785         3.276263
min    1970.000000    123.993000        70.600000
25%    1985.250000   1038.357000        75.525000
50%    1998.000000   2295.578000        78.100000
75%    2009.000000   4055.610000        80.575000
max    2020.000000  11859.179000        84.700000

- Include all columns in summary

In [11]:
df.describe(include='all')

               Year Country  Spending_USD  Life_Expectancy
count    274.000000     274    274.000000       274.000000
unique          NaN       6           NaN              NaN
top             NaN     USA           NaN              NaN
freq            NaN      51           NaN              NaN
mean    1996.992701     NaN   2789.338905        77.909489
std       14.180933     NaN   2194.939785         3.276263
min     1970.000000     NaN    123.993000        70.600000
25%     1985.250000     NaN   1038.357000        75.525000
50%     1998.000000     NaN   2295.578000        78.100000
75%     2009.000000     NaN   4055.610000        80.575000
max     2020.000000     NaN  11859.179000        84.700000

- Count missing values

In [12]:
df.isnull().sum()

Year               0
Country            0
Spending_USD       0
Life_Expectancy    0
dtype: int64

- Check if any missing value exists.

In [13]:
df.isnull().values.any()

np.False_

- Count duplicate rows.

In [14]:
df.duplicated().sum()

np.int64(0)

- Remove duplicates

In [15]:
df.drop_duplicates()

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

-  Display random 5 rows.

In [16]:
df.sample(5)

     Year        Country  Spending_USD  Life_Expectancy
200  2008          Japan      2799.198             82.7
146  1999          Japan      1667.922             80.5
31   1978          Japan       392.577             75.7
231  2013            USA      8519.620             78.8
199  2008  Great Britain      3207.853             79.8

- Display random 10 rows

In [17]:
df.sample(10)

     Year  Country  Spending_USD  Life_Expectancy
112  1994   Canada      1962.196             77.9
165  2002      USA      5316.522             77.0
10   1972  Germany       337.364             71.0
255  2017      USA     10046.472             78.6
54   1983  Germany      1104.594             73.8
3    1970    Japan       150.437             72.0
78   1987      USA      1976.166             74.9
108  1993   France      1753.485             77.5
147  1999      USA      4261.996             76.7
178  2005   Canada      3291.912             80.0

- Check memory usage.

In [18]:
df.memory_usage()

Index               132
Year               2192
Country            2192
Spending_USD       2192
Life_Expectancy    2192
dtype: int64

## ***Column Operations***

- Display only Country column.

In [19]:
df[["Country"]]

           Country
0          Germany
1           France
2    Great Britain
3            Japan
4              USA
..             ...
269        Germany
270         France
271  Great Britain
272          Japan
273            USA

[274 rows x 1 columns]

In [20]:
df["Country"].value_counts()

Country
USA              51
Japan            51
Germany          50
Canada           44
Great Britain    43
France           35
Name: count, dtype: int64

- Select Country and Year

In [21]:
df[["Country","Year"]]

           Country  Year
0          Germany  1970
1           France  1970
2    Great Britain  1970
3            Japan  1970
4              USA  1970
..             ...   ...
269        Germany  2020
270         France  2020
271  Great Britain  2020
272          Japan  2020
273            USA  2020

[274 rows x 2 columns]

- Get unique countries

In [22]:
df["Country"].unique()

array(['Germany', 'France', 'Great Britain', 'Japan', 'USA', 'Canada'],
      dtype=object)

-  Count unique countries.

In [23]:
df["Country"].nunique()

6

- Count records per country.

In [24]:
df["Country"].value_counts()

Country
USA              51
Japan            51
Germany          50
Canada           44
Great Britain    43
France           35
Name: count, dtype: int64

- Sort country names.

In [25]:
sorted(df["Country"].unique())

['Canada', 'France', 'Germany', 'Great Britain', 'Japan', 'USA']

- Display column list.

In [26]:
list(df.columns)

['Year', 'Country', 'Spending_USD', 'Life_Expectancy']

- Rename Country column.

In [27]:
df.rename(columns={"Country":"Nation"})

     Year         Nation  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

- Convert column names to lowercase.

In [28]:
df.columns = df.columns.str.lower()
df.columns

Index(['year', 'country', 'spending_usd', 'life_expectancy'], dtype='object')

## ***Filtering***

- Show records for Germany.

In [31]:
df[df["Country"]=="Germany"]

     Year  Country  Spending_USD  Life_Expectancy
0    1970  Germany       252.311             70.6
6    1971  Germany       298.251             70.8
10   1972  Germany       337.364             71.0
13   1973  Germany       384.541             71.3
16   1974  Germany       452.744             71.5
19   1975  Germany       532.481             71.4
24   1976  Germany       591.098             71.8
27   1977  Germany       647.352             72.5
30   1978  Germany       729.457             72.4
34   1979  Germany       800.703             72.8
38   1980  Germany       908.166             72.9
44   1981  Germany      1014.713             73.2
49   1982  Germany      1044.528             73.5
54   1983  Germany      1104.594             73.8
59   1984  Germany      1196.560             74.3
64   1985  Germany      1298.555             75.0
70   1986  Germany      1386.510             75.2
75   1987  Germany      1480.096             75.6
80   1988  Germany      1616.349             75.9
85   1989  Germany      1596.160             76.0
90   1990  Germany      1724.332             77.3
101  1992  Germany      2019.308             76.1
107  1993  Germany      2040.313             76.1
113  1994  Germany      2188.676             76.5
119  1995  Germany      2349.145             76.6
125  1996  Germany      2480.217             76.9
131  1997  Germany      2496.201             77.3
137  1998  Germany      2566.003             77.7
143  1999  Germany      2697.878             77.9
149  2000  Germany      2895.533             78.2
155  2001  Germany      3009.368             78.5
161  2002  Germany      3239.770             78.5
167  2003  Germany      3329.374             78.6
173  2004  Germany      3391.521             79.2
179  2005  Germany      3429.955             79.4
185  2006  Germany      3567.061             79.8
191  2007  Germany      3750.787             80.1
197  2008  Germany      3955.136             80.2
203  2009  Germany      4158.266             80.3
209  2010  Germany      4423.070             80.5
215  2011  Germany      4566.678             80.5
221  2012  Germany      4745.546             80.6
227  2013  Germany      4951.677             80.6
233  2014  Germany      5151.709             81.2
239  2015  Germany      5295.975             80.7
245  2016  Germany      5669.064             81.0
251  2017  Germany      5970.163             81.1
257  2018  Germany      6281.840             81.0
263  2019  Germany      6407.928             81.3
269  2020  Germany      6938.983             81.1

- Show records for USA.

In [32]:
df[df["Country"]=="USA"]

     Year Country  Spending_USD  Life_Expectancy
4    1970     USA       326.961             70.9
9    1971     USA       357.988             71.2
12   1972     USA       397.097             71.2
15   1973     USA       439.302             71.4
18   1974     USA       495.114             72.0
22   1975     USA       560.750             72.7
26   1976     USA       638.851             72.9
29   1977     USA       726.241             73.3
32   1978     USA       808.884             73.5
36   1979     USA       908.963             73.9
42   1980     USA      1036.300             73.7
47   1981     USA      1191.537             74.1
52   1982     USA      1329.669             74.5
57   1983     USA      1451.945             74.6
62   1984     USA      1590.667             74.7
68   1985     USA      1735.156             74.7
73   1986     USA      1847.773             74.7
78   1987     USA      1976.166             74.9
83   1988     USA      2195.392             74.9
88   1989     USA      2424.654             75.1
94   1990     USA      2684.984             75.3
99   1991     USA      2901.589             75.5
105  1992     USA      3100.343             75.7
111  1993     USA      3286.558             75.5
117  1994     USA      3432.101             75.7
123  1995     USA      3586.745             75.7
129  1996     USA      4158.928             76.1
135  1997     USA      3894.282             76.5
141  1998     USA      4061.536             76.7
147  1999     USA      4261.996             76.7
153  2000     USA      4536.561             76.7
159  2001     USA      4888.518             76.9
165  2002     USA      5316.522             77.0
171  2003     USA      5726.538             77.1
177  2004     USA      6069.530             77.6
183  2005     USA      6430.757             77.6
189  2006     USA      6808.054             77.8
195  2007     USA      7166.513             78.1
201  2008     USA      7385.026             78.1
207  2009     USA      7645.002             78.5
213  2010     USA      7879.253             78.6
219  2011     USA      8079.467             78.7
225  2012     USA      8346.064             78.8
231  2013     USA      8519.620             78.8
237  2014     USA      8925.879             78.9
243  2015     USA      9355.118             78.7
249  2016     USA      9717.649             78.7
255  2017     USA     10046.472             78.6
261  2018     USA     10451.386             78.7
267  2019     USA     10855.517             78.8
273  2020     USA     11859.179             77.0

- Show data after 2010.

In [33]:
df[df["Year"]>2010]

     Year        Country  Spending_USD  Life_Expectancy
214  2011         Canada      4228.962             81.4
215  2011        Germany      4566.678             80.5
216  2011         France      4161.698             82.3
217  2011  Great Britain      3495.652             81.0
218  2011          Japan      3740.756             82.7
219  2011            USA      8079.467             78.7
220  2012         Canada      4336.249             81.6
221  2012        Germany      4745.546             80.6
222  2012         France      4299.434             82.1
223  2012  Great Britain      3614.131             81.0
224  2012          Japan      3970.765             83.2
225  2012            USA      8346.064             78.8
226  2013         Canada      4428.753             81.7
227  2013        Germany      4951.677             80.6
228  2013         France      4544.964             82.3
229  2013  Great Britain      3667.636             81.1
230  2013          Japan      4308.252             83.4
231  2013            USA      8519.620             78.8
232  2014         Canada      4536.810             81.8
233  2014        Germany      5151.709             81.2
234  2014         France      4626.679             82.8
235  2014  Great Britain      3758.935             81.4
236  2014          Japan      4328.364             83.7
237  2014            USA      8925.879             78.9
238  2015         Canada      4635.285             81.9
239  2015        Germany      5295.975             80.7
240  2015         France      4667.156             82.4
241  2015  Great Britain      3805.820             81.0
242  2015          Japan      4515.556             83.9
243  2015            USA      9355.118             78.7
244  2016         Canada      5044.275             82.0
245  2016        Germany      5669.064             81.0
246  2016         France      4928.128             82.7
247  2016  Great Britain      3960.141             81.2
248  2016          Japan      4295.858             84.1
249  2016            USA      9717.649             78.7
250  2017         Canada      5150.470             81.9
251  2017        Germany      5970.163             81.1
252  2017         France      5005.756             82.7
253  2017  Great Britain      4059.125             81.3
254  2017          Japan      4412.852             84.2
255  2017            USA     10046.472             78.6
256  2018         Canada      5308.356             82.0
257  2018        Germany      6281.840             81.0
258  2018         France      5099.306             82.8
259  2018  Great Britain      4189.708             81.3
260  2018          Japan      4554.276             84.3
261  2018            USA     10451.386             78.7
262  2019         Canada      5189.721             82.2
263  2019        Germany      6407.928             81.3
264  2019         France      5167.839             82.9
265  2019  Great Britain      4385.463             81.4
266  2019          Japan      4610.794             84.4
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

- Show data before 2000

In [34]:
df[df["Year"]<2000]

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
143  1999        Germany      2697.878             77.9
144  1999         France      2431.303             78.9
145  1999  Great Britain      1683.905             77.5
146  1999          Japan      1667.922             80.5
147  1999            USA      4261.996             76.7

[148 rows x 4 columns]

- Show records for France after 2010.

In [35]:
df[(df["Country"]=="France") & (df["Year"]>2010)]

     Year Country  Spending_USD  Life_Expectancy
216  2011  France      4161.698             82.3
222  2012  France      4299.434             82.1
228  2013  France      4544.964             82.3
234  2014  France      4626.679             82.8
240  2015  France      4667.156             82.4
246  2016  France      4928.128             82.7
252  2017  France      5005.756             82.7
258  2018  France      5099.306             82.8
264  2019  France      5167.839             82.9
270  2020  France      5468.418             82.3

- Show records for Germany or France.

In [36]:
df[df["Country"].isin(["Germany","France"])]

     Year  Country  Spending_USD  Life_Expectancy
0    1970  Germany       252.311             70.6
1    1970   France       192.143             72.2
6    1971  Germany       298.251             70.8
10   1972  Germany       337.364             71.0
13   1973  Germany       384.541             71.3
..    ...      ...           ...              ...
258  2018   France      5099.306             82.8
263  2019  Germany      6407.928             81.3
264  2019   France      5167.839             82.9
269  2020  Germany      6938.983             81.1
270  2020   France      5468.418             82.3

[85 rows x 4 columns]

- Show life expectancy above 80.

In [37]:
df[df["Life_Expectancy"]>80]

     Year        Country  Spending_USD  Life_Expectancy
128  1996          Japan      1436.372             80.3
134  1997          Japan      1529.586             80.5
140  1998          Japan      1571.107             80.6
146  1999          Japan      1667.922             80.5
152  2000          Japan      1847.786             81.2
..    ...            ...           ...              ...
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7

[83 rows x 4 columns]

- Show spending above 5000.

In [38]:
df[df["Spending_USD"]>5000]

     Year        Country  Spending_USD  Life_Expectancy
165  2002            USA      5316.522             77.0
171  2003            USA      5726.538             77.1
177  2004            USA      6069.530             77.6
183  2005            USA      6430.757             77.6
189  2006            USA      6808.054             77.8
195  2007            USA      7166.513             78.1
201  2008            USA      7385.026             78.1
207  2009            USA      7645.002             78.5
213  2010            USA      7879.253             78.6
219  2011            USA      8079.467             78.7
225  2012            USA      8346.064             78.8
231  2013            USA      8519.620             78.8
233  2014        Germany      5151.709             81.2
237  2014            USA      8925.879             78.9
239  2015        Germany      5295.975             80.7
243  2015            USA      9355.118             78.7
244  2016         Canada      5044.275             82.0
245  2016        Germany      5669.064             81.0
249  2016            USA      9717.649             78.7
250  2017         Canada      5150.470             81.9
251  2017        Germany      5970.163             81.1
252  2017         France      5005.756             82.7
255  2017            USA     10046.472             78.6
256  2018         Canada      5308.356             82.0
257  2018        Germany      6281.840             81.0
258  2018         France      5099.306             82.8
261  2018            USA     10451.386             78.7
262  2019         Canada      5189.721             82.2
263  2019        Germany      6407.928             81.3
264  2019         France      5167.839             82.9
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
273  2020            USA     11859.179             77.0

- Filter multiple countries.

In [39]:
df[df["Country"].isin(["USA","Canada","Japan"])]

     Year Country  Spending_USD  Life_Expectancy
3    1970   Japan       150.437             72.0
4    1970     USA       326.961             70.9
5    1971  Canada       313.391             72.8
8    1971   Japan       163.854             72.9
9    1971     USA       357.988             71.2
..    ...     ...           ...              ...
266  2019   Japan      4610.794             84.4
267  2019     USA     10855.517             78.8
268  2020  Canada      5828.324             81.7
272  2020   Japan      4665.641             84.7
273  2020     USA     11859.179             77.0

[146 rows x 4 columns]

- Exclude USA

In [40]:
df[df["Country"]!="USA"]

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
5    1971         Canada       313.391             72.8
..    ...            ...           ...              ...
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7

[223 rows x 4 columns]

## ***Sorting***

- Sort by Year ascending.

In [41]:
df.sort_values("Year")

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

- Sort by Year descending.

In [42]:
df.sort_values("Year",ascending=False)

     Year        Country  Spending_USD  Life_Expectancy
273  2020            USA     11859.179             77.0
272  2020          Japan      4665.641             84.7
271  2020  Great Britain      5018.700             80.4
270  2020         France      5468.418             82.3
269  2020        Germany      6938.983             81.1
..    ...            ...           ...              ...
4    1970            USA       326.961             70.9
3    1970          Japan       150.437             72.0
2    1970  Great Britain       123.993             71.9
1    1970         France       192.143             72.2
0    1970        Germany       252.311             70.6

[274 rows x 4 columns]

- Sort by Life Expectancy.

In [43]:
df.sort_values("Life_Expectancy")

     Year  Country  Spending_USD  Life_Expectancy
0    1970  Germany       252.311             70.6
6    1971  Germany       298.251             70.8
4    1970      USA       326.961             70.9
10   1972  Germany       337.364             71.0
9    1971      USA       357.988             71.2
..    ...      ...           ...              ...
248  2016    Japan      4295.858             84.1
254  2017    Japan      4412.852             84.2
260  2018    Japan      4554.276             84.3
266  2019    Japan      4610.794             84.4
272  2020    Japan      4665.641             84.7

[274 rows x 4 columns]

- Sort by expenditure descending

In [44]:
df.sort_values("Spending_USD",ascending=False)

     Year        Country  Spending_USD  Life_Expectancy
273  2020            USA     11859.179             77.0
267  2019            USA     10855.517             78.8
261  2018            USA     10451.386             78.7
255  2017            USA     10046.472             78.6
249  2016            USA      9717.649             78.7
..    ...            ...           ...              ...
11   1972          Japan       185.390             73.2
8    1971          Japan       163.854             72.9
3    1970          Japan       150.437             72.0
7    1971  Great Britain       134.172             71.9
2    1970  Great Britain       123.993             71.9

[274 rows x 4 columns]

- Sort by Country then Year.

In [45]:
df.sort_values(["Country","Year"])

     Year Country  Spending_USD  Life_Expectancy
5    1971  Canada       313.391             72.8
23   1976  Canada       543.337             73.8
33   1979  Canada       692.269             75.1
37   1980  Canada       791.812             75.2
43   1981  Canada       898.807             75.5
..    ...     ...           ...              ...
249  2016     USA      9717.649             78.7
255  2017     USA     10046.472             78.6
261  2018     USA     10451.386             78.7
267  2019     USA     10855.517             78.8
273  2020     USA     11859.179             77.0

[274 rows x 4 columns]

## ***Aggregation***

- Average life expectancy.

In [46]:
df["Life_Expectancy"].mean()

np.float64(77.90948905109488)

- Maximum life expectancy.

In [47]:
df["Life_Expectancy"].max()

np.float64(84.7)

- Minimum life expectancy

In [48]:
df["Life_Expectancy"].min()

np.float64(70.6)

- Median life expectancy.

In [49]:
df["Life_Expectancy"].median()

np.float64(78.1)

- Standard deviation

In [50]:
df["Life_Expectancy"].std()

np.float64(3.276263466523638)

- Average expenditure.

In [51]:
df["Spending_USD"].mean()

np.float64(2789.338905109489)

- Total expenditure

In [52]:
df["Spending_USD"].sum()

np.float64(764278.86)

- Highest expenditure

In [53]:
df["Spending_USD"].max()

np.float64(11859.179)

- Lowest expenditure

In [54]:
df["Spending_USD"].min()

np.float64(123.993)

- Range of expenditure.

In [55]:
df["Spending_USD"].max()-df["Spending_USD"].min()

np.float64(11735.186)

## ***GroupBy***

- Average life expectancy by country.

In [56]:
df.groupby("Country")["Life_Expectancy"].mean()

Country
Canada           78.706818
France           79.565714
Germany          76.726000
Great Britain    77.620930
Japan            79.554902
USA              75.843137
Name: Life_Expectancy, dtype: float64

- Maximum life expectancy by country

In [57]:
df.groupby("Country")["Life_Expectancy"].max()

Country
Canada           82.2
France           82.9
Germany          81.3
Great Britain    81.4
Japan            84.7
USA              78.9
Name: Life_Expectancy, dtype: float64

- Minimum life expectancy by country.

In [58]:
df.groupby("Country")["Life_Expectancy"].min()

Country
Canada           72.8
France           72.2
Germany          70.6
Great Britain    71.9
Japan            72.0
USA              70.9
Name: Life_Expectancy, dtype: float64

- Average expenditure by country.

In [59]:
df.groupby("Country")["Spending_USD"].mean()

Country
Canada           2685.778341
France           3045.145057
Germany          2667.280200
Great Britain    2034.192465
Japan            1860.257902
USA              4388.570529
Name: Spending_USD, dtype: float64

- Total expenditure by country.

In [60]:
df.groupby("Country")["Spending_USD"].sum()

Country
Canada           118174.247
France           106580.077
Germany          133364.010
Great Britain     87470.276
Japan             94873.153
USA              223817.097
Name: Spending_USD, dtype: float64

- Count rows per country

In [61]:
df.groupby("Country").size()

Country
Canada           44
France           35
Germany          50
Great Britain    43
Japan            51
USA              51
dtype: int64

- Multiple aggregations.

In [62]:
df.groupby("Country")["Life_Expectancy"].agg(["mean","min","max"])

                    mean   min   max
Country
Canada         78.706818  72.8  82.2
France         79.565714  72.2  82.9
Germany        76.726000  70.6  81.3
Great Britain  77.620930  71.9  81.4
Japan          79.554902  72.0  84.7
USA            75.843137  70.9  78.9

- Average by year

In [63]:
df.groupby("Year")["Life_Expectancy"].mean()

Year
1970    71.520000
1971    71.920000
1972    71.800000
1973    72.033333
1974    72.400000
1975    72.850000
1976    73.325000
1977    73.700000
1978    73.866667
1979    74.500000
1980    74.233333
1981    74.620000
1982    74.920000
1983    75.120000
1984    75.420000
1985    75.616667
1986    75.860000
1987    76.180000
1988    76.260000
1989    76.480000
1990    76.916667
1991    77.060000
1992    77.100000
1993    77.083333
1994    77.450000
1995    77.450000
1996    77.766667
1997    78.066667
1998    78.283333
1999    78.383333
2000    78.716667
2001    78.950000
2002    79.083333
2003    79.133333
2004    79.683333
2005    79.766667
2006    80.150000
2007    80.366667
2008    80.483333
2009    80.766667
2010    80.933333
2011    81.100000
2012    81.216667
2013    81.316667
2014    81.633333
2015    81.433333
2016    81.616667
2017    81.633333
2018    81.683333
2019    81.833333
2020    81.200000
Name: Life_Expectancy, dtype: float64

-  Maximum expenditure by year.

In [64]:
df.groupby("Year")["Spending_USD"].max()

Year
1970      326.961
1971      357.988
1972      397.097
1973      439.302
1974      495.114
1975      560.750
1976      638.851
1977      726.241
1978      808.884
1979      908.963
1980     1036.300
1981     1191.537
1982     1329.669
1983     1451.945
1984     1590.667
1985     1735.156
1986     1847.773
1987     1976.166
1988     2195.392
1989     2424.654
1990     2684.984
1991     2901.589
1992     3100.343
1993     3286.558
1994     3432.101
1995     3586.745
1996     4158.928
1997     3894.282
1998     4061.536
1999     4261.996
2000     4536.561
2001     4888.518
2002     5316.522
2003     5726.538
2004     6069.530
2005     6430.757
2006     6808.054
2007     7166.513
2008     7385.026
2009     7645.002
2010     7879.253
2011     8079.467
2012     8346.064
2013     8519.620
2014     8925.879
2015     9355.118
2016     9717.649
2017    10046.472
2018    10451.386
2019    10855.517
2020    11859.179
Name: Spending_USD, dtype: float64

- Minimum expenditure by year.

In [65]:
df.groupby("Year")["Spending_USD"].min()

Year
1970     123.993
1971     134.172
1972     185.390
1973     205.778
1974     242.018
1975     284.269
1976     303.725
1977     340.628
1978     392.577
1979     452.931
1980     385.099
1981     433.957
1982     448.477
1983     501.924
1984     521.522
1985     549.608
1986     578.610
1987     634.956
1988     688.049
1989     739.714
1990     782.612
1991     842.797
1992     930.701
1993     995.728
1994    1058.680
1995    1094.034
1996    1171.591
1997    1507.352
1998    1571.107
1999    1667.922
2000    1847.786
2001    1945.556
2002    2065.133
2003    2194.437
2004    2303.680
2005    2471.186
2006    2561.219
2007    2689.916
2008    2799.198
2009    2971.377
2010    3169.190
2011    3495.652
2012    3614.131
2013    3667.636
2014    3758.935
2015    3805.820
2016    3960.141
2017    4059.125
2018    4189.708
2019    4385.463
2020    4665.641
Name: Spending_USD, dtype: float64

## ***Indexing***

- First row using iloc.

In [66]:
df.iloc[0]

Year                  1970
Country            Germany
Spending_USD       252.311
Life_Expectancy       70.6
Name: 0, dtype: object

- First five rows.

In [67]:
df.iloc[:5]

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

- First row and first column

In [68]:
df.iloc[0,0]

np.int64(1970)

- Select rows 10-20

In [69]:
df.iloc[10:21]

    Year  Country  Spending_USD  Life_Expectancy
10  1972  Germany       337.364             71.0
11  1972    Japan       185.390             73.2
12  1972      USA       397.097             71.2
13  1973  Germany       384.541             71.3
14  1973    Japan       205.778             73.4
15  1973      USA       439.302             71.4
16  1974  Germany       452.744             71.5
17  1974    Japan       242.018             73.7
18  1974      USA       495.114             72.0
19  1975  Germany       532.481             71.4
20  1975   France       363.610             73.0

- Select specific columns.

In [70]:
df.iloc[:,0:3]

     Year        Country  Spending_USD
0    1970        Germany       252.311
1    1970         France       192.143
2    1970  Great Britain       123.993
3    1970          Japan       150.437
4    1970            USA       326.961
..    ...            ...           ...
269  2020        Germany      6938.983
270  2020         France      5468.418
271  2020  Great Britain      5018.700
272  2020          Japan      4665.641
273  2020            USA     11859.179

[274 rows x 3 columns]

## ***Query Method***

- Germany records using query.

In [71]:
df.query("Country=='Germany'")

     Year  Country  Spending_USD  Life_Expectancy
0    1970  Germany       252.311             70.6
6    1971  Germany       298.251             70.8
10   1972  Germany       337.364             71.0
13   1973  Germany       384.541             71.3
16   1974  Germany       452.744             71.5
19   1975  Germany       532.481             71.4
24   1976  Germany       591.098             71.8
27   1977  Germany       647.352             72.5
30   1978  Germany       729.457             72.4
34   1979  Germany       800.703             72.8
38   1980  Germany       908.166             72.9
44   1981  Germany      1014.713             73.2
49   1982  Germany      1044.528             73.5
54   1983  Germany      1104.594             73.8
59   1984  Germany      1196.560             74.3
64   1985  Germany      1298.555             75.0
70   1986  Germany      1386.510             75.2
75   1987  Germany      1480.096             75.6
80   1988  Germany      1616.349             75.9
85   1989  Germany      1596.160             76.0
90   1990  Germany      1724.332             77.3
101  1992  Germany      2019.308             76.1
107  1993  Germany      2040.313             76.1
113  1994  Germany      2188.676             76.5
119  1995  Germany      2349.145             76.6
125  1996  Germany      2480.217             76.9
131  1997  Germany      2496.201             77.3
137  1998  Germany      2566.003             77.7
143  1999  Germany      2697.878             77.9
149  2000  Germany      2895.533             78.2
155  2001  Germany      3009.368             78.5
161  2002  Germany      3239.770             78.5
167  2003  Germany      3329.374             78.6
173  2004  Germany      3391.521             79.2
179  2005  Germany      3429.955             79.4
185  2006  Germany      3567.061             79.8
191  2007  Germany      3750.787             80.1
197  2008  Germany      3955.136             80.2
203  2009  Germany      4158.266             80.3
209  2010  Germany      4423.070             80.5
215  2011  Germany      4566.678             80.5
221  2012  Germany      4745.546             80.6
227  2013  Germany      4951.677             80.6
233  2014  Germany      5151.709             81.2
239  2015  Germany      5295.975             80.7
245  2016  Germany      5669.064             81.0
251  2017  Germany      5970.163             81.1
257  2018  Germany      6281.840             81.0
263  2019  Germany      6407.928             81.3
269  2020  Germany      6938.983             81.1

- Year greater than 2015.

In [72]:
df.query("Year>2015")

     Year        Country  Spending_USD  Life_Expectancy
244  2016         Canada      5044.275             82.0
245  2016        Germany      5669.064             81.0
246  2016         France      4928.128             82.7
247  2016  Great Britain      3960.141             81.2
248  2016          Japan      4295.858             84.1
249  2016            USA      9717.649             78.7
250  2017         Canada      5150.470             81.9
251  2017        Germany      5970.163             81.1
252  2017         France      5005.756             82.7
253  2017  Great Britain      4059.125             81.3
254  2017          Japan      4412.852             84.2
255  2017            USA     10046.472             78.6
256  2018         Canada      5308.356             82.0
257  2018        Germany      6281.840             81.0
258  2018         France      5099.306             82.8
259  2018  Great Britain      4189.708             81.3
260  2018          Japan      4554.276             84.3
261  2018            USA     10451.386             78.7
262  2019         Canada      5189.721             82.2
263  2019        Germany      6407.928             81.3
264  2019         France      5167.839             82.9
265  2019  Great Britain      4385.463             81.4
266  2019          Japan      4610.794             84.4
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

- Life expectancy above 82.

In [73]:
df.query("Life_Expectancy>82")

     Year Country  Spending_USD  Life_Expectancy
176  2004   Japan      2303.680             82.1
188  2006   Japan      2561.219             82.4
194  2007   Japan      2689.916             82.6
200  2008   Japan      2799.198             82.7
206  2009   Japan      2971.377             83.0
212  2010   Japan      3169.190             82.9
216  2011  France      4161.698             82.3
218  2011   Japan      3740.756             82.7
222  2012  France      4299.434             82.1
224  2012   Japan      3970.765             83.2
228  2013  France      4544.964             82.3
230  2013   Japan      4308.252             83.4
234  2014  France      4626.679             82.8
236  2014   Japan      4328.364             83.7
240  2015  France      4667.156             82.4
242  2015   Japan      4515.556             83.9
246  2016  France      4928.128             82.7
248  2016   Japan      4295.858             84.1
252  2017  France      5005.756             82.7
254  2017   Japan      4412.852             84.2
258  2018  France      5099.306             82.8
260  2018   Japan      4554.276             84.3
262  2019  Canada      5189.721             82.2
264  2019  France      5167.839             82.9
266  2019   Japan      4610.794             84.4
270  2020  France      5468.418             82.3
272  2020   Japan      4665.641             84.7

- Expenditure above 4000.

In [74]:
df.query("Spending_USD>4000")

     Year        Country  Spending_USD  Life_Expectancy
129  1996            USA      4158.928             76.1
141  1998            USA      4061.536             76.7
147  1999            USA      4261.996             76.7
153  2000            USA      4536.561             76.7
159  2001            USA      4888.518             76.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[70 rows x 4 columns]

- Germany after 2010

In [75]:
df.query("Country=='Germany' and Year>2010")

     Year  Country  Spending_USD  Life_Expectancy
215  2011  Germany      4566.678             80.5
221  2012  Germany      4745.546             80.6
227  2013  Germany      4951.677             80.6
233  2014  Germany      5151.709             81.2
239  2015  Germany      5295.975             80.7
245  2016  Germany      5669.064             81.0
251  2017  Germany      5970.163             81.1
257  2018  Germany      6281.840             81.0
263  2019  Germany      6407.928             81.3
269  2020  Germany      6938.983             81.1

## ***Advanced Analysis***

- Top 5 highest life expectancy rows.

In [76]:
df.nlargest(5,"Life_Expectancy")

     Year Country  Spending_USD  Life_Expectancy
272  2020   Japan      4665.641             84.7
266  2019   Japan      4610.794             84.4
260  2018   Japan      4554.276             84.3
254  2017   Japan      4412.852             84.2
248  2016   Japan      4295.858             84.1

- Lowest 5 life expectancy rows.

In [77]:
df.nsmallest(5,"Life_Expectancy")

    Year  Country  Spending_USD  Life_Expectancy
0   1970  Germany       252.311             70.6
6   1971  Germany       298.251             70.8
4   1970      USA       326.961             70.9
10  1972  Germany       337.364             71.0
9   1971      USA       357.988             71.2

- Top expenditure records.

In [78]:
df.nlargest(10,"Spending_USD")

     Year Country  Spending_USD  Life_Expectancy
273  2020     USA     11859.179             77.0
267  2019     USA     10855.517             78.8
261  2018     USA     10451.386             78.7
255  2017     USA     10046.472             78.6
249  2016     USA      9717.649             78.7
243  2015     USA      9355.118             78.7
237  2014     USA      8925.879             78.9
231  2013     USA      8519.620             78.8
225  2012     USA      8346.064             78.8
219  2011     USA      8079.467             78.7

- Bottom expenditure records.

In [79]:
df.nsmallest(10,"Spending_USD")

    Year        Country  Spending_USD  Life_Expectancy
2   1970  Great Britain       123.993             71.9
7   1971  Great Britain       134.172             71.9
3   1970          Japan       150.437             72.0
8   1971          Japan       163.854             72.9
11  1972          Japan       185.390             73.2
1   1970         France       192.143             72.2
14  1973          Japan       205.778             73.4
17  1974          Japan       242.018             73.7
0   1970        Germany       252.311             70.6
21  1975          Japan       284.269             74.3

- Correlation matrix

In [80]:
df.corr(numeric_only=True)

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

## ***Pivot Tables***

- Average life expectancy pivot.

In [81]:
pd.pivot_table(df,index="Country",
               values="Life_Expectancy")

               Life_Expectancy
Country
Canada               78.706818
France               79.565714
Germany              76.726000
Great Britain        77.620930
Japan                79.554902
USA                  75.843137

- Average expenditure pivot.

In [82]:
pd.pivot_table(df,index="Country",
               values="Spending_USD")

               Spending_USD
Country
Canada          2685.778341
France          3045.145057
Germany         2667.280200
Great Britain   2034.192465
Japan           1860.257902
USA             4388.570529

- Country-Year pivot.

In [83]:
pd.pivot_table(df,index="Country",
               columns="Year",
               values="Life_Expectancy")

Year,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country,,,,,,,,,,,,,,,,,,,,,
Canada,NaN,72.8,NaN,NaN,NaN,NaN,73.8,NaN,NaN,75.1,...,81.4,81.6,81.7,81.8,81.9,82.0,81.9,82.0,82.2,81.7
France,72.2,NaN,NaN,NaN,NaN,73.0,NaN,NaN,NaN,NaN,...,82.3,82.1,82.3,82.8,82.4,82.7,82.7,82.8,82.9,82.3
Germany,70.6,70.8,71.0,71.3,71.5,71.4,71.8,72.5,72.4,72.8,...,80.5,80.6,80.6,81.2,80.7,81.0,81.1,81.0,81.3,81.1
Great Britain,71.9,71.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.0,81.0,81.1,81.4,81.0,81.2,81.3,81.3,81.4,80.4
Japan,72.0,72.9,73.2,73.4,73.7,74.3,74.8,75.3,75.7,76.2,...,82.7,83.2,83.4,83.7,83.9,84.1,84.2,84.3,84.4,84.7
USA,70.9,71.2,71.2,71.4,72.0,72.7,72.9,73.3,73.5,73.9,...,78.7,78.8,78.8,78.9,78.7,78.7,78.6,78.7,78.8,77.0

- Max expenditure pivot.

In [84]:
pd.pivot_table(df,index="Country",
               values="Spending_USD",
               aggfunc="max")

               Spending_USD
Country
Canada             5828.324
France             5468.418
Germany            6938.983
Great Britain      5018.700
Japan              4665.641
USA               11859.179

- Min expenditure pivot.

In [85]:
pd.pivot_table(df,index="Country",
               values="Spending_USD",
               aggfunc="min")

               Spending_USD
Country
Canada              313.391
France              192.143
Germany             252.311
Great Britain       123.993
Japan               150.437
USA                 326.961

## ***Transformations***

- Create expenditure in thousands.

In [86]:
df["Exp_K"]=df["Spending_USD"]/1000
df.describe()

              Year  Spending_USD  Life_Expectancy       Exp_K
count   274.000000    274.000000       274.000000  274.000000
mean   1996.992701   2789.338905        77.909489    2.789339
std      14.180933   2194.939785         3.276263    2.194940
min    1970.000000    123.993000        70.600000    0.123993
25%    1985.250000   1038.357000        75.525000    1.038357
50%    1998.000000   2295.578000        78.100000    2.295578
75%    2009.000000   4055.610000        80.575000    4.055610
max    2020.000000  11859.179000        84.700000   11.859179

- Create life expectancy category.

In [87]:
df["Category"]=pd.cut(df["Life_Expectancy"],
                      bins=[0,75,80,100],
                      labels=["Low","Medium","High"])
df.groupby("Category")

C:\Users\Geershati Saxena\AppData\Local\Temp\ipykernel_7780\3725470826.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Category")

- Add constant value.

In [88]:
df["Life_Expectancy"]+1

0      71.6
1      73.2
2      72.9
3      73.0
4      71.9
       ...
269    82.1
270    83.3
271    81.4
272    85.7
273    78.0
Name: Life_Expectancy, Length: 274, dtype: float64

- Multiply expenditure by 10%.

In [89]:
df["Spending_USD"]*1.10

0        277.5421
1        211.3573
2        136.3923
3        165.4807
4        359.6571
          ...
269     7632.8813
270     6015.2598
271     5520.5700
272     5132.2051
273    13045.0969
Name: Spending_USD, Length: 274, dtype: float64

- Round expenditure.

In [90]:
df["Spending_USD"].round()

0        252.0
1        192.0
2        124.0
3        150.0
4        327.0
        ...
269     6939.0
270     5468.0
271     5019.0
272     4666.0
273    11859.0
Name: Spending_USD, Length: 274, dtype: float64

## ***String Operations***

- Convert country names to uppercase.

In [91]:
df["Country"].str.upper()

0            GERMANY
1             FRANCE
2      GREAT BRITAIN
3              JAPAN
4                USA
           ...
269          GERMANY
270           FRANCE
271    GREAT BRITAIN
272            JAPAN
273              USA
Name: Country, Length: 274, dtype: object

In [92]:
df

     Year        Country  Spending_USD  Life_Expectancy      Exp_K Category
0    1970        Germany       252.311             70.6   0.252311      Low
1    1970         France       192.143             72.2   0.192143      Low
2    1970  Great Britain       123.993             71.9   0.123993      Low
3    1970          Japan       150.437             72.0   0.150437      Low
4    1970            USA       326.961             70.9   0.326961      Low
..    ...            ...           ...              ...        ...      ...
269  2020        Germany      6938.983             81.1   6.938983     High
270  2020         France      5468.418             82.3   5.468418     High
271  2020  Great Britain      5018.700             80.4   5.018700     High
272  2020          Japan      4665.641             84.7   4.665641     High
273  2020            USA     11859.179             77.0  11.859179   Medium

[274 rows x 6 columns]

- Country name lengths.

In [93]:
df["Country"].str.len()

0       7
1       6
2      13
3       5
4       3
       ..
269     7
270     6
271    13
272     5
273     3
Name: Country, Length: 274, dtype: int64

- Convert country names to lowercase

In [94]:
df["Country"].str.lower()

0            germany
1             france
2      great britain
3              japan
4                usa
           ...
269          germany
270           france
271    great britain
272            japan
273              usa
Name: Country, Length: 274, dtype: object

- Countries starting with U.

In [95]:
df[df["Country"].str.startswith("U")]

     Year Country  Spending_USD  Life_Expectancy      Exp_K Category
4    1970     USA       326.961             70.9   0.326961      Low
9    1971     USA       357.988             71.2   0.357988      Low
12   1972     USA       397.097             71.2   0.397097      Low
15   1973     USA       439.302             71.4   0.439302      Low
18   1974     USA       495.114             72.0   0.495114      Low
22   1975     USA       560.750             72.7   0.560750      Low
26   1976     USA       638.851             72.9   0.638851      Low
29   1977     USA       726.241             73.3   0.726241      Low
32   1978     USA       808.884             73.5   0.808884      Low
36   1979     USA       908.963             73.9   0.908963      Low
42   1980     USA      1036.300             73.7   1.036300      Low
47   1981     USA      1191.537             74.1   1.191537      Low
52   1982     USA      1329.669             74.5   1.329669      Low
57   1983     USA      1451.945             74.6   1.451945      Low
62   1984     USA      1590.667             74.7   1.590667      Low
68   1985     USA      1735.156             74.7   1.735156      Low
73   1986     USA      1847.773             74.7   1.847773      Low
78   1987     USA      1976.166             74.9   1.976166      Low
83   1988     USA      2195.392             74.9   2.195392      Low
88   1989     USA      2424.654             75.1   2.424654   Medium
94   1990     USA      2684.984             75.3   2.684984   Medium
99   1991     USA      2901.589             75.5   2.901589   Medium
105  1992     USA      3100.343             75.7   3.100343   Medium
111  1993     USA      3286.558             75.5   3.286558   Medium
117  1994     USA      3432.101             75.7   3.432101   Medium
123  1995     USA      3586.745             75.7   3.586745   Medium
129  1996     USA      4158.928             76.1   4.158928   Medium
135  1997     USA      3894.282             76.5   3.894282   Medium
141  1998     USA      4061.536             76.7   4.061536   Medium
147  1999     USA      4261.996             76.7   4.261996   Medium
153  2000     USA      4536.561             76.7   4.536561   Medium
159  2001     USA      4888.518             76.9   4.888518   Medium
165  2002     USA      5316.522             77.0   5.316522   Medium
171  2003     USA      5726.538             77.1   5.726538   Medium
177  2004     USA      6069.530             77.6   6.069530   Medium
183  2005     USA      6430.757             77.6   6.430757   Medium
189  2006     USA      6808.054             77.8   6.808054   Medium
195  2007     USA      7166.513             78.1   7.166513   Medium
201  2008     USA      7385.026             78.1   7.385026   Medium
207  2009     USA      7645.002             78.5   7.645002   Medium
213  2010     USA      7879.253             78.6   7.879253   Medium
219  2011     USA      8079.467             78.7   8.079467   Medium
225  2012     USA      8346.064             78.8   8.346064   Medium
231  2013     USA      8519.620             78.8   8.519620   Medium
237  2014     USA      8925.879             78.9   8.925879   Medium
243  2015     USA      9355.118             78.7   9.355118   Medium
249  2016     USA      9717.649             78.7   9.717649   Medium
255  2017     USA     10046.472             78.6  10.046472   Medium
261  2018     USA     10451.386             78.7  10.451386   Medium
267  2019     USA     10855.517             78.8  10.855517   Medium
273  2020     USA     11859.179             77.0  11.859179   Medium

## ***Miscellaneous***

- Display unique years

In [96]:
df["Year"].unique()

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020])

- Count unique years.

In [97]:
df["Year"].nunique()

51

- Find latest year

In [98]:
df["Year"].max()

np.int64(2020)

- Find earliest year.

In [99]:
df["Year"].min()

np.int64(1970)

- Country with highest average life expectancy.

In [100]:
df.groupby("Country")["Life_Expectancy"].mean().idxmax()

'France'

- Country with lowest average life expectancy

In [101]:
df.groupby("Country")["Life_Expectancy"].mean().idxmin()

'USA'

- Country with highest average expenditure.

In [102]:
df.groupby("Country")["Spending_USD"].mean().idxmax()

'USA'

- Country with lowest average expenditure

In [103]:
df.groupby("Country")["Spending_USD"].mean().idxmin()

'Japan'

- Find the country with the highest life expectancy in each year.

In [104]:
df.loc[df.groupby("Year")["Life_Expectancy"].idxmax(),
       ["Year", "Country", "Life_Expectancy"]]

     Year Country  Life_Expectancy
1    1970  France             72.2
8    1971   Japan             72.9
11   1972   Japan             73.2
14   1973   Japan             73.4
17   1974   Japan             73.7
21   1975   Japan             74.3
25   1976   Japan             74.8
28   1977   Japan             75.3
31   1978   Japan             75.7
35   1979   Japan             76.2
41   1980   Japan             76.1
46   1981   Japan             76.5
51   1982   Japan             76.9
56   1983   Japan             77.0
61   1984   Japan             77.4
67   1985   Japan             77.6
72   1986   Japan             78.1
77   1987   Japan             78.5
82   1988   Japan             78.4
87   1989   Japan             78.8
93   1990   Japan             78.9
98   1991   Japan             79.1
104  1992   Japan             79.2
110  1993   Japan             79.4
116  1994   Japan             79.8
122  1995   Japan             79.6
128  1996   Japan             80.3
134  1997   Japan             80.5
140  1998   Japan             80.6
146  1999   Japan             80.5
152  2000   Japan             81.2
158  2001   Japan             81.5
164  2002   Japan             81.8
170  2003   Japan             81.8
176  2004   Japan             82.1
182  2005   Japan             82.0
188  2006   Japan             82.4
194  2007   Japan             82.6
200  2008   Japan             82.7
206  2009   Japan             83.0
212  2010   Japan             82.9
218  2011   Japan             82.7
224  2012   Japan             83.2
230  2013   Japan             83.4
236  2014   Japan             83.7
242  2015   Japan             83.9
248  2016   Japan             84.1
254  2017   Japan             84.2
260  2018   Japan             84.3
266  2019   Japan             84.4
272  2020   Japan             84.7

- Find the country with the lowest life expectancy in each year.

In [105]:
df.loc[df.groupby("Year")["Life_Expectancy"].idxmin(),
       ["Year", "Country", "Life_Expectancy"]]

     Year        Country  Life_Expectancy
0    1970        Germany             70.6
6    1971        Germany             70.8
10   1972        Germany             71.0
13   1973        Germany             71.3
16   1974        Germany             71.5
19   1975        Germany             71.4
24   1976        Germany             71.8
27   1977        Germany             72.5
30   1978        Germany             72.4
34   1979        Germany             72.8
38   1980        Germany             72.9
44   1981        Germany             73.2
49   1982        Germany             73.5
54   1983        Germany             73.8
59   1984        Germany             74.3
66   1985  Great Britain             74.7
73   1986            USA             74.7
78   1987            USA             74.9
83   1988            USA             74.9
88   1989            USA             75.1
94   1990            USA             75.3
99   1991            USA             75.5
105  1992            USA             75.7
111  1993            USA             75.5
117  1994            USA             75.7
123  1995            USA             75.7
129  1996            USA             76.1
135  1997            USA             76.5
141  1998            USA             76.7
147  1999            USA             76.7
153  2000            USA             76.7
159  2001            USA             76.9
165  2002            USA             77.0
171  2003            USA             77.1
177  2004            USA             77.6
183  2005            USA             77.6
189  2006            USA             77.8
195  2007            USA             78.1
201  2008            USA             78.1
207  2009            USA             78.5
213  2010            USA             78.6
219  2011            USA             78.7
225  2012            USA             78.8
231  2013            USA             78.8
237  2014            USA             78.9
243  2015            USA             78.7
249  2016            USA             78.7
255  2017            USA             78.6
261  2018            USA             78.7
267  2019            USA             78.8
273  2020            USA             77.0

- Calculate cumulative health expenditure for each country

In [107]:
df["Cumulative_Expenditure"] = (
    df.groupby("Country")["Spending_USD"].cumsum()
)
df["Cumulative_Expenditure"]

0         252.311
1         192.143
2         123.993
3         150.437
4         326.961
          ...
269    133364.010
270    106580.077
271     87470.276
272     94873.153
273    223817.097
Name: Cumulative_Expenditure, Length: 274, dtype: float64

- Calculate cumulative average life expectancy for each country

In [109]:
df["CumAvg_Life_Expectancy"] = (
    df.groupby("Country")["Life_Expectancy"]
      .expanding()
      .mean()
      .reset_index(level=0, drop=True)
)
df["CumAvg_Life_Expectancy"]

0      70.600000
1      72.200000
2      71.900000
3      72.000000
4      70.900000
         ...
269    76.726000
270    79.565714
271    77.620930
272    79.554902
273    75.843137
Name: CumAvg_Life_Expectancy, Length: 274, dtype: float64

- Find the percentage change in health expenditure for each country

In [110]:
df["Exp_Percent_Change"] = (
    df.groupby("Country")["Spending_USD"]
      .pct_change() * 100
)

- Find the year-over-year difference in life expectancy for each country

In [115]:
df["LifeExp_Difference"] = (
    df.groupby("Country")["Life_Expectancy"]
      .diff()
)

- Rank countries by health expenditure within each year.

In [113]:
df["Exp_Rank"] = (
    df.groupby("Year")["Spending_USD"]
      .rank(ascending=False)
)

- Find the top 3 countries by life expectancy in each year.

In [116]:
top3 = (
    df.groupby("Year", group_keys=False)
      .apply(lambda x: x.nlargest(3, "Life_Expectancy"))
)

C:\Users\Geershati Saxena\AppData\Local\Temp\ipykernel_7780\2656987382.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.nlargest(3, "Life_Expectancy"))

- Create a MultiIndex using Country and Year.

In [118]:
df["Rolling_3yr_Exp"] = (
    df.groupby("Country")["Spending_USD"]
      .transform(lambda x: x.rolling(3).mean())
)

- Find the rolling 3-year average health expenditure for each country.

In [119]:
df["Rolling_3yr_Exp"] = (
    df.groupby("Country")["Spending_USD"]
      .transform(lambda x: x.rolling(3).mean())
)

- Export dataset to CSV.

In [120]:
df.to_csv("healthexp.csv",index=False)