# ***Pandas Questions & Answers Using Seaborn's healthexp Dataset***

- Loading the Libraries

In [1]:
import pandas as pd
import seaborn as sns

- Loading the Dataset

In [2]:
df = sns.load_dataset("healthexp")
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

- Display first 10 rows.

In [3]:
df.head(10)

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9
5  1971         Canada       313.391             72.8
6  1971        Germany       298.251             70.8
7  1971  Great Britain       134.172             71.9
8  1971          Japan       163.854             72.9
9  1971            USA       357.988             71.2

Display last 10 rows.

In [4]:
df.tail(10)

     Year        Country  Spending_USD  Life_Expectancy
264  2019         France      5167.839             82.9
265  2019  Great Britain      4385.463             81.4
266  2019          Japan      4610.794             84.4
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

- Display dataset shape.

In [5]:
df.shape

(274, 4)

- Count rows.

In [6]:
len(df)

274

- Display column names

In [7]:
df.columns

Index(['Year', 'Country', 'Spending_USD', 'Life_Expectancy'], dtype='object')

- Show data types

In [8]:
df.dtypes

Year                 int64
Country             object
Spending_USD       float64
Life_Expectancy    float64
dtype: object

- Get dataset information.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             274 non-null    int64
 1   Country          274 non-null    object
 2   Spending_USD     274 non-null    float64
 3   Life_Expectancy  274 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 8.7+ KB

- Display summary statistics

In [10]:
df.describe()

              Year  Spending_USD  Life_Expectancy
count   274.000000    274.000000       274.000000
mean   1996.992701   2789.338905        77.909489
std      14.180933   2194.939785         3.276263
min    1970.000000    123.993000        70.600000
25%    1985.250000   1038.357000        75.525000
50%    1998.000000   2295.578000        78.100000
75%    2009.000000   4055.610000        80.575000
max    2020.000000  11859.179000        84.700000

- Include all columns in summary

In [11]:
df.describe(include='all')

               Year Country  Spending_USD  Life_Expectancy
count    274.000000     274    274.000000       274.000000
unique          NaN       6           NaN              NaN
top             NaN     USA           NaN              NaN
freq            NaN      51           NaN              NaN
mean    1996.992701     NaN   2789.338905        77.909489
std       14.180933     NaN   2194.939785         3.276263
min     1970.000000     NaN    123.993000        70.600000
25%     1985.250000     NaN   1038.357000        75.525000
50%     1998.000000     NaN   2295.578000        78.100000
75%     2009.000000     NaN   4055.610000        80.575000
max     2020.000000     NaN  11859.179000        84.700000

- Count missing values

In [12]:
df.isnull().sum()

Year               0
Country            0
Spending_USD       0
Life_Expectancy    0
dtype: int64

- Check if any missing value exists.

In [13]:
df.isnull().values.any()

np.False_

- Count duplicate rows.

In [14]:
df.duplicated().sum()

np.int64(0)

- Remove duplicates

In [15]:
df.drop_duplicates()

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

-  Display random 5 rows.

In [16]:
df.sample(5)

     Year        Country  Spending_USD  Life_Expectancy
58   1984         Canada      1135.020             76.2
164  2002          Japan      2065.133             81.8
44   1981        Germany      1014.713             73.2
102  1992         France      1651.139             77.5
55   1983  Great Britain       501.924             74.3

- Display random 10 rows

In [17]:
df.sample(10)

     Year        Country  Spending_USD  Life_Expectancy
66   1985  Great Britain       549.608             74.7
212  2010          Japan      3169.190             82.9
238  2015         Canada      4635.285             81.9
197  2008        Germany      3955.136             80.2
115  1994  Great Britain      1058.680             76.8
102  1992         France      1651.139             77.5
243  2015            USA      9355.118             78.7
182  2005          Japan      2471.186             82.0
50   1982  Great Britain       448.477             74.1
71   1986  Great Britain       578.610             74.8

- Check memory usage.

In [18]:
df.memory_usage()

Index               132
Year               2192
Country            2192
Spending_USD       2192
Life_Expectancy    2192
dtype: int64

## ***Column Operations***

- Display only Country column.

In [24]:
df[["Country"]]

           Country
0          Germany
1           France
2    Great Britain
3            Japan
4              USA
..             ...
269        Germany
270         France
271  Great Britain
272          Japan
273            USA

[274 rows x 1 columns]

In [22]:
df["Country"].value_counts()

Country
USA              51
Japan            51
Germany          50
Canada           44
Great Britain    43
France           35
Name: count, dtype: int64

- Select Country and Year

In [23]:
df[["Country","Year"]]

           Country  Year
0          Germany  1970
1           France  1970
2    Great Britain  1970
3            Japan  1970
4              USA  1970
..             ...   ...
269        Germany  2020
270         France  2020
271  Great Britain  2020
272          Japan  2020
273            USA  2020

[274 rows x 2 columns]

- Get unique countries

In [28]:
df["Country"].unique()

array(['Germany', 'France', 'Great Britain', 'Japan', 'USA', 'Canada'],
      dtype=object)

-  Count unique countries.

In [29]:
df["Country"].nunique()

6

- Count records per country.

In [30]:
df["Country"].value_counts()

Country
USA              51
Japan            51
Germany          50
Canada           44
Great Britain    43
France           35
Name: count, dtype: int64

- Sort country names.

In [31]:
sorted(df["Country"].unique())

['Canada', 'France', 'Germany', 'Great Britain', 'Japan', 'USA']

- Display column list.

In [32]:
list(df.columns)

['Year', 'Country', 'Spending_USD', 'Life_Expectancy']

- Rename Country column.

In [33]:
df.rename(columns={"Country":"Nation"})

     Year         Nation  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]