# ***Pandas Questions & Answers Using Seaborn's healthexp Dataset***

- Loading the Libraries

In [1]:
import pandas as pd
import seaborn as sns

- Loading the Dataset

In [30]:
df = sns.load_dataset("healthexp")
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

- Display first 10 rows.

In [3]:
df.head(10)

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9
5  1971         Canada       313.391             72.8
6  1971        Germany       298.251             70.8
7  1971  Great Britain       134.172             71.9
8  1971          Japan       163.854             72.9
9  1971            USA       357.988             71.2

Display last 10 rows.

In [4]:
df.tail(10)

     Year        Country  Spending_USD  Life_Expectancy
264  2019         France      5167.839             82.9
265  2019  Great Britain      4385.463             81.4
266  2019          Japan      4610.794             84.4
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

- Display dataset shape.

In [5]:
df.shape

(274, 4)

- Count rows.

In [6]:
len(df)

274

- Display column names

In [7]:
df.columns

Index(['Year', 'Country', 'Spending_USD', 'Life_Expectancy'], dtype='object')

- Show data types

In [8]:
df.dtypes

Year                 int64
Country             object
Spending_USD       float64
Life_Expectancy    float64
dtype: object

- Get dataset information.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             274 non-null    int64
 1   Country          274 non-null    object
 2   Spending_USD     274 non-null    float64
 3   Life_Expectancy  274 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 8.7+ KB

- Display summary statistics

In [10]:
df.describe()

              Year  Spending_USD  Life_Expectancy
count   274.000000    274.000000       274.000000
mean   1996.992701   2789.338905        77.909489
std      14.180933   2194.939785         3.276263
min    1970.000000    123.993000        70.600000
25%    1985.250000   1038.357000        75.525000
50%    1998.000000   2295.578000        78.100000
75%    2009.000000   4055.610000        80.575000
max    2020.000000  11859.179000        84.700000

- Include all columns in summary

In [11]:
df.describe(include='all')

               Year Country  Spending_USD  Life_Expectancy
count    274.000000     274    274.000000       274.000000
unique          NaN       6           NaN              NaN
top             NaN     USA           NaN              NaN
freq            NaN      51           NaN              NaN
mean    1996.992701     NaN   2789.338905        77.909489
std       14.180933     NaN   2194.939785         3.276263
min     1970.000000     NaN    123.993000        70.600000
25%     1985.250000     NaN   1038.357000        75.525000
50%     1998.000000     NaN   2295.578000        78.100000
75%     2009.000000     NaN   4055.610000        80.575000
max     2020.000000     NaN  11859.179000        84.700000

- Count missing values

In [12]:
df.isnull().sum()

Year               0
Country            0
Spending_USD       0
Life_Expectancy    0
dtype: int64

- Check if any missing value exists.

In [13]:
df.isnull().values.any()

np.False_

- Count duplicate rows.

In [14]:
df.duplicated().sum()

np.int64(0)

- Remove duplicates

In [15]:
df.drop_duplicates()

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

-  Display random 5 rows.

In [16]:
df.sample(5)

     Year        Country  Spending_USD  Life_Expectancy
230  2013          Japan      4308.252             83.4
198  2008         France      3729.353             81.4
179  2005        Germany      3429.955             79.4
127  1996  Great Britain      1171.591             76.9
222  2012         France      4299.434             82.1

- Display random 10 rows

In [17]:
df.sample(10)

     Year        Country  Spending_USD  Life_Expectancy
105  1992            USA      3100.343             75.7
27   1977        Germany       647.352             72.5
102  1992         France      1651.139             77.5
232  2014         Canada      4536.810             81.8
164  2002          Japan      2065.133             81.8
2    1970  Great Britain       123.993             71.9
207  2009            USA      7645.002             78.5
29   1977            USA       726.241             73.3
226  2013         Canada      4428.753             81.7
122  1995          Japan      1413.445             79.6

- Check memory usage.

In [18]:
df.memory_usage()

Index               132
Year               2192
Country            2192
Spending_USD       2192
Life_Expectancy    2192
dtype: int64

## ***Column Operations***

- Display only Country column.

In [19]:
df[["Country"]]

           Country
0          Germany
1           France
2    Great Britain
3            Japan
4              USA
..             ...
269        Germany
270         France
271  Great Britain
272          Japan
273            USA

[274 rows x 1 columns]

In [20]:
df["Country"].value_counts()

Country
USA              51
Japan            51
Germany          50
Canada           44
Great Britain    43
France           35
Name: count, dtype: int64

- Select Country and Year

In [21]:
df[["Country","Year"]]

           Country  Year
0          Germany  1970
1           France  1970
2    Great Britain  1970
3            Japan  1970
4              USA  1970
..             ...   ...
269        Germany  2020
270         France  2020
271  Great Britain  2020
272          Japan  2020
273            USA  2020

[274 rows x 2 columns]

- Get unique countries

In [22]:
df["Country"].unique()

array(['Germany', 'France', 'Great Britain', 'Japan', 'USA', 'Canada'],
      dtype=object)

-  Count unique countries.

In [23]:
df["Country"].nunique()

6

- Count records per country.

In [24]:
df["Country"].value_counts()

Country
USA              51
Japan            51
Germany          50
Canada           44
Great Britain    43
France           35
Name: count, dtype: int64

- Sort country names.

In [25]:
sorted(df["Country"].unique())

['Canada', 'France', 'Germany', 'Great Britain', 'Japan', 'USA']

- Display column list.

In [26]:
list(df.columns)

['Year', 'Country', 'Spending_USD', 'Life_Expectancy']

- Rename Country column.

In [27]:
df.rename(columns={"Country":"Nation"})

     Year         Nation  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

- Convert column names to lowercase.

In [28]:
df.columns = df.columns.str.lower()
df.columns

Index(['year', 'country', 'spending_usd', 'life_expectancy'], dtype='object')

## ***Filtering***

- Show records for Germany.

In [31]:
df[df["Country"]=="Germany"]

     Year  Country  Spending_USD  Life_Expectancy
0    1970  Germany       252.311             70.6
6    1971  Germany       298.251             70.8
10   1972  Germany       337.364             71.0
13   1973  Germany       384.541             71.3
16   1974  Germany       452.744             71.5
19   1975  Germany       532.481             71.4
24   1976  Germany       591.098             71.8
27   1977  Germany       647.352             72.5
30   1978  Germany       729.457             72.4
34   1979  Germany       800.703             72.8
38   1980  Germany       908.166             72.9
44   1981  Germany      1014.713             73.2
49   1982  Germany      1044.528             73.5
54   1983  Germany      1104.594             73.8
59   1984  Germany      1196.560             74.3
64   1985  Germany      1298.555             75.0
70   1986  Germany      1386.510             75.2
75   1987  Germany      1480.096             75.6
80   1988  Germany      1616.349             75.9
85   1989  Germany      1596.160             76.0
90   1990  Germany      1724.332             77.3
101  1992  Germany      2019.308             76.1
107  1993  Germany      2040.313             76.1
113  1994  Germany      2188.676             76.5
119  1995  Germany      2349.145             76.6
125  1996  Germany      2480.217             76.9
131  1997  Germany      2496.201             77.3
137  1998  Germany      2566.003             77.7
143  1999  Germany      2697.878             77.9
149  2000  Germany      2895.533             78.2
155  2001  Germany      3009.368             78.5
161  2002  Germany      3239.770             78.5
167  2003  Germany      3329.374             78.6
173  2004  Germany      3391.521             79.2
179  2005  Germany      3429.955             79.4
185  2006  Germany      3567.061             79.8
191  2007  Germany      3750.787             80.1
197  2008  Germany      3955.136             80.2
203  2009  Germany      4158.266             80.3
209  2010  Germany      4423.070             80.5
215  2011  Germany      4566.678             80.5
221  2012  Germany      4745.546             80.6
227  2013  Germany      4951.677             80.6
233  2014  Germany      5151.709             81.2
239  2015  Germany      5295.975             80.7
245  2016  Germany      5669.064             81.0
251  2017  Germany      5970.163             81.1
257  2018  Germany      6281.840             81.0
263  2019  Germany      6407.928             81.3
269  2020  Germany      6938.983             81.1

- Show records for USA.

In [ ]:
df[df["Country"]=="USA"]

     Year Country  Spending_USD  Life_Expectancy
4    1970     USA       326.961             70.9
9    1971     USA       357.988             71.2
12   1972     USA       397.097             71.2
15   1973     USA       439.302             71.4
18   1974     USA       495.114             72.0
22   1975     USA       560.750             72.7
26   1976     USA       638.851             72.9
29   1977     USA       726.241             73.3
32   1978     USA       808.884             73.5
36   1979     USA       908.963             73.9
42   1980     USA      1036.300             73.7
47   1981     USA      1191.537             74.1
52   1982     USA      1329.669             74.5
57   1983     USA      1451.945             74.6
62   1984     USA      1590.667             74.7
68   1985     USA      1735.156             74.7
73   1986     USA      1847.773             74.7
78   1987     USA      1976.166             74.9
83   1988     USA      2195.392             74.9
88   1989     USA      2424.654             75.1
94   1990     USA      2684.984             75.3
99   1991     USA      2901.589             75.5
105  1992     USA      3100.343             75.7
111  1993     USA      3286.558             75.5
117  1994     USA      3432.101             75.7
123  1995     USA      3586.745             75.7
129  1996     USA      4158.928             76.1
135  1997     USA      3894.282             76.5
141  1998     USA      4061.536             76.7
147  1999     USA      4261.996             76.7
153  2000     USA      4536.561             76.7
159  2001     USA      4888.518             76.9
165  2002     USA      5316.522             77.0
171  2003     USA      5726.538             77.1
177  2004     USA      6069.530             77.6
183  2005     USA      6430.757             77.6
189  2006     USA      6808.054             77.8
195  2007     USA      7166.513             78.1
201  2008     USA      7385.026             78.1
207  2009     USA      7645.002             78.5
213  2010     USA      7879.253             78.6
219  2011     USA      8079.467             78.7
225  2012     USA      8346.064             78.8
231  2013     USA      8519.620             78.8
237  2014     USA      8925.879             78.9
243  2015     USA      9355.118             78.7
249  2016     USA      9717.649             78.7
255  2017     USA     10046.472             78.6
261  2018     USA     10451.386             78.7
267  2019     USA     10855.517             78.8
273  2020     USA     11859.179             77.0

- Show data after 2010.

In [32]:
df[df["Year"]>2010]

     Year        Country  Spending_USD  Life_Expectancy
214  2011         Canada      4228.962             81.4
215  2011        Germany      4566.678             80.5
216  2011         France      4161.698             82.3
217  2011  Great Britain      3495.652             81.0
218  2011          Japan      3740.756             82.7
219  2011            USA      8079.467             78.7
220  2012         Canada      4336.249             81.6
221  2012        Germany      4745.546             80.6
222  2012         France      4299.434             82.1
223  2012  Great Britain      3614.131             81.0
224  2012          Japan      3970.765             83.2
225  2012            USA      8346.064             78.8
226  2013         Canada      4428.753             81.7
227  2013        Germany      4951.677             80.6
228  2013         France      4544.964             82.3
229  2013  Great Britain      3667.636             81.1
230  2013          Japan      4308.252             83.4
231  2013            USA      8519.620             78.8
232  2014         Canada      4536.810             81.8
233  2014        Germany      5151.709             81.2
234  2014         France      4626.679             82.8
235  2014  Great Britain      3758.935             81.4
236  2014          Japan      4328.364             83.7
237  2014            USA      8925.879             78.9
238  2015         Canada      4635.285             81.9
239  2015        Germany      5295.975             80.7
240  2015         France      4667.156             82.4
241  2015  Great Britain      3805.820             81.0
242  2015          Japan      4515.556             83.9
243  2015            USA      9355.118             78.7
244  2016         Canada      5044.275             82.0
245  2016        Germany      5669.064             81.0
246  2016         France      4928.128             82.7
247  2016  Great Britain      3960.141             81.2
248  2016          Japan      4295.858             84.1
249  2016            USA      9717.649             78.7
250  2017         Canada      5150.470             81.9
251  2017        Germany      5970.163             81.1
252  2017         France      5005.756             82.7
253  2017  Great Britain      4059.125             81.3
254  2017          Japan      4412.852             84.2
255  2017            USA     10046.472             78.6
256  2018         Canada      5308.356             82.0
257  2018        Germany      6281.840             81.0
258  2018         France      5099.306             82.8
259  2018  Great Britain      4189.708             81.3
260  2018          Japan      4554.276             84.3
261  2018            USA     10451.386             78.7
262  2019         Canada      5189.721             82.2
263  2019        Germany      6407.928             81.3
264  2019         France      5167.839             82.9
265  2019  Great Britain      4385.463             81.4
266  2019          Japan      4610.794             84.4
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

- Show data before 2000

In [33]:
df[df["Year"]<2000]

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
143  1999        Germany      2697.878             77.9
144  1999         France      2431.303             78.9
145  1999  Great Britain      1683.905             77.5
146  1999          Japan      1667.922             80.5
147  1999            USA      4261.996             76.7

[148 rows x 4 columns]

- Show records for France after 2010.

In [34]:
df[(df["Country"]=="France") & (df["Year"]>2010)]

     Year Country  Spending_USD  Life_Expectancy
216  2011  France      4161.698             82.3
222  2012  France      4299.434             82.1
228  2013  France      4544.964             82.3
234  2014  France      4626.679             82.8
240  2015  France      4667.156             82.4
246  2016  France      4928.128             82.7
252  2017  France      5005.756             82.7
258  2018  France      5099.306             82.8
264  2019  France      5167.839             82.9
270  2020  France      5468.418             82.3

- Show records for Germany or France.

In [35]:
df[df["Country"].isin(["Germany","France"])]

     Year  Country  Spending_USD  Life_Expectancy
0    1970  Germany       252.311             70.6
1    1970   France       192.143             72.2
6    1971  Germany       298.251             70.8
10   1972  Germany       337.364             71.0
13   1973  Germany       384.541             71.3
..    ...      ...           ...              ...
258  2018   France      5099.306             82.8
263  2019  Germany      6407.928             81.3
264  2019   France      5167.839             82.9
269  2020  Germany      6938.983             81.1
270  2020   France      5468.418             82.3

[85 rows x 4 columns]

- Show life expectancy above 80.

In [36]:
df[df["Life_Expectancy"]>80]

     Year        Country  Spending_USD  Life_Expectancy
128  1996          Japan      1436.372             80.3
134  1997          Japan      1529.586             80.5
140  1998          Japan      1571.107             80.6
146  1999          Japan      1667.922             80.5
152  2000          Japan      1847.786             81.2
..    ...            ...           ...              ...
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7

[83 rows x 4 columns]

- Show spending above 5000.

In [39]:
df[df["Spending_USD"]>5000]

     Year        Country  Spending_USD  Life_Expectancy
165  2002            USA      5316.522             77.0
171  2003            USA      5726.538             77.1
177  2004            USA      6069.530             77.6
183  2005            USA      6430.757             77.6
189  2006            USA      6808.054             77.8
195  2007            USA      7166.513             78.1
201  2008            USA      7385.026             78.1
207  2009            USA      7645.002             78.5
213  2010            USA      7879.253             78.6
219  2011            USA      8079.467             78.7
225  2012            USA      8346.064             78.8
231  2013            USA      8519.620             78.8
233  2014        Germany      5151.709             81.2
237  2014            USA      8925.879             78.9
239  2015        Germany      5295.975             80.7
243  2015            USA      9355.118             78.7
244  2016         Canada      5044.275             82.0
245  2016        Germany      5669.064             81.0
249  2016            USA      9717.649             78.7
250  2017         Canada      5150.470             81.9
251  2017        Germany      5970.163             81.1
252  2017         France      5005.756             82.7
255  2017            USA     10046.472             78.6
256  2018         Canada      5308.356             82.0
257  2018        Germany      6281.840             81.0
258  2018         France      5099.306             82.8
261  2018            USA     10451.386             78.7
262  2019         Canada      5189.721             82.2
263  2019        Germany      6407.928             81.3
264  2019         France      5167.839             82.9
267  2019            USA     10855.517             78.8
268  2020         Canada      5828.324             81.7
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
273  2020            USA     11859.179             77.0

   Year  Country  Spending_USD  Life_Expectancy
0  1970  Germany       252.311             70.6